CREATE TABLE tracker (
    id_tracker int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_person int NOT NULL,
    ito_tracker_code VARCHAR(36) UNIQUE NOT NULL,
    created_at DATE DEFAULT now() NOT NULL,
    latitude int(11,8) NOT NULL,
    longitude int(11,8) NOT NULL,

    CONSTRAINT tracker_person_fk FOREIGN KEY (id_person)
        REFERENCES person(id_person)
);