CREATE TABLE itouser (
    id_user int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email varchar UNIQUE NOT NULL,
    password int NOT NULL,
    role int NOT NULL CHECK ( role in ('ADMIN', 'USER') )
);